### ISSUE TITLE
Assignment view

### ISSUE THREAD

**Issue by krashanoff** [cs130-w22/Group-A3#10]
## Epic
Students and teachers should both have varied views of an assignment's summary. For students, this may include information such as their most recent submissions, while for professors this may include things like their entire class' most recent submissions, menus to change the grading script, and more.

![student assignment view](https://user-images.githubusercontent.com/7704542/149213395-3674e8b4-06ff-4a8d-89d1-1928d405f474.png)

## User Stories
- [x] #52
- [ ] As a student, I need a way to view my assignment's score form in real-time after submitting to understand its performance.
- [ ] As a student, I need a way to track my assignments' scores over past submissions.
- [x] #53
- [ ] As a professor, I need a way to choose which test cases to expose to students for grading feedback.
- [ ] As a professor, I need a way to export student grades for a given assignment into another format (CSV, JSON, etc.) for use with my own software.
