### ISSUE TITLE
Student View

### ISSUE THREAD

**Issue by krashanoff** [cs130-w22/Group-A3#5]
## Epic
Students need to have a custom view of the system, displaying which classes they are enrolled in, their assignments, their submissions, and more. Through this view, they should be able to upload code to assignments, as well.

## User Stories
- [ ] As a student, I need an easy way to log in to my view to access my classes.
- [ ] As a student, I need an obvious overview of my classes to view assignments.
- [ ] As a student, I need an obvious overview of my assignments to understand what my workload is like.
- [ ] As a student, I need a way to submit my code to an assignment, so that I may get it graded.
- [ ] As a student, I need a way to view my assignment's score form in real-time after submitting to understand its performance.
- [ ] As a student, I need a way to track my assignments' scores over past submissions.
