### ISSUE TITLE
Teacher View

### ISSUE THREAD

**Issue by krashanoff** [cs130-w22/Group-A3#6]
## Epic
Teaching faculty require ways to create classes, assignments, and grading procedures for their students to get reliable feedback. This should be conducted through a unified view, through which operations with the system are obvious and predictable.

## User Stories
- [ ] As a professor, I need a way to create a new class to let my students join.
- [ ] As a professor, I need a way to enroll students into my class.
- [ ] As a professor, I need a way to create a new assignment within a class to let my students submit their work.
- [ ] As a professor, I need a way to upload or specify a grading script to an assignment to grade an assignment.
- [ ] As a professor, I need a way to choose which test cases to expose to students for grading feedback.
- [ ] As a professor, I need a way to export student grades for a given assignment into another format (CSV, JSON, etc.) for use with my own software.
