### ISSUE TITLE
Enrich assignment view

### ISSUE THREAD

**Issue by krashanoff** [cs130-w22/Group-A3#7]
## Epic
Something that we can do to truly distinguish ourselves from closed-source alternatives to this grading server is provide both student and teacher with a data-rich view of their submissions and their students' submissions, respectively. These enhancements should *improve* the user experience compared to the MVP rendition. There should be no regression in capability or intuitiveness; rather they should make the interface more valuable.

## User Stories
- [ ] As a student, I want to see my best and worst submission.
- [ ] As a professor, I want to view my entire classes score distribution for a given assignment to assist me in the curving process.
- [ ] As a student, I want to view my submission scores and feedback over time to understand where I have been improving my code and where I haven't.
